version: 1.0.{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
install:
  - IF NOT EXIST vcpkg git clone --depth 1 https://github.com/Microsoft/vcpkg  
  - cd vcpkg
  - git fetch --depth=1
  - git reset --hard origin/master
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg.exe remove --outdated --recurse
  - vcpkg install zlib:%PLATFORM%-windows-static
  - vcpkg install pcre:%PLATFORM%-windows-static
  - vcpkg install libffi:%PLATFORM%-windows-static
  - vcpkg install gettext:%PLATFORM%-windows-static
  - vcpkg install libiconv:%PLATFORM%-windows-static
  - vcpkg install glib:%PLATFORM%-windows-static
  - vcpkg install libpng:%PLATFORM%-windows-static
  - vcpkg install pixman:%PLATFORM%-windows-static
  - vcpkg install bzip2:%PLATFORM%-windows-static
  - vcpkg install freetype:%PLATFORM%-windows-static
  - vcpkg install expat:%PLATFORM%-windows-static
  - vcpkg install fontconfig:%PLATFORM%-windows-static
  - vcpkg install cairo:%PLATFORM%-windows-static
  - vcpkg install harfbuzz:%PLATFORM%-windows-static
######
  - vcpkg install pango:%PLATFORM%-windows-static
######
  - vcpkg install libjpeg-turbo:%PLATFORM%-windows-static
  - vcpkg install libwebp:%PLATFORM%-windows-static
  - vcpkg install liblzma:%PLATFORM%-windows-static
  - vcpkg install tiff:%PLATFORM%-windows-static
######
  - vcpkg install libgd:%PLATFORM%-windows-static
  - vcpkg install wxwidgets:%PLATFORM%-windows-static
######
  - vcpkg integrate install
  - IF EXIST buildtrees rmdir /s /q buildtrees
  - IF EXIST downloads rmdir /s /q downloads
  - IF EXIST packages rmdir /s /q packages
  - cd ..
cache:
  - vcpkg
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -mx
build:
  project: config\msvc\gnuplot\gnuplot.sln
  verbosity: minimal
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
artifacts:
  - path: config\msvc\gnuplot\$(platform)\$(configuration)
    name: gnuplot_$(platform)_$(configuration)
    type: zip
