version: 1.0.{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
install:
  - vcpkg install zlib:%PLATFORM%-windows
  - vcpkg install pcre:%PLATFORM%-windows
  - vcpkg install libffi:%PLATFORM%-windows
  - vcpkg install gettext:%PLATFORM%-windows
  - vcpkg install libiconv:%PLATFORM%-windows
  - vcpkg install glib:%PLATFORM%-windows
  - vcpkg install libpng:%PLATFORM%-windows
  - vcpkg install pixman:%PLATFORM%-windows
  - vcpkg install bzip2:%PLATFORM%-windows
  - vcpkg install freetype:%PLATFORM%-windows
  - vcpkg install expat:%PLATFORM%-windows
  - vcpkg install fontconfig:%PLATFORM%-windows
  - vcpkg install cairo:%PLATFORM%-windows
  - vcpkg install --recurse harfbuzz[core,glib,ucdn]:%PLATFORM%-windows
######
  - vcpkg install pango:%PLATFORM%-windows
######
  - vcpkg install libjpeg-turbo:%PLATFORM%-windows
  - vcpkg install libwebp:%PLATFORM%-windows
  - vcpkg install liblzma:%PLATFORM%-windows
  - vcpkg install tiff:%PLATFORM%-windows
######
  - vcpkg install libgd:%PLATFORM%-windows
  - vcpkg install wxwidgets:%PLATFORM%-windows
cache:
  - c:\tools\vcpkg\installed\
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -mx
build:
  project: config\msvc\gnuplot\gnuplot.sln
  verbosity: normal
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
artifacts:
  - path: config\msvc\gnuplot\$(platform)\$(configuration)
    name: gnuplot_$(platform)_$(configuration)
    type: zip
