version: 1.0.{build}
branches:
  only:
  - main
  - dev
image: Visual Studio 2019
install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - .\vcpkg.exe install --recurse pango:%PLATFORM%-windows
  - .\vcpkg.exe install --recurse libgd:%PLATFORM%-windows
  - .\vcpkg.exe install --recurse wxwidgets:%PLATFORM%-windows
  - .\vcpkg.exe integrate install
cache:
  - c:\tools\vcpkg\installed\
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -mx
build:
  project: config\msvc\gnuplot\gnuplot.sln
  verbosity: normal
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
artifacts:
  - path: config\msvc\gnuplot\$(platform)\$(configuration)
    name: gnuplot_$(platform)_$(configuration)
    type: zip
deploy:
  provider: GitHub
  auth_token:
    secure: 2Uyv3KkcTbdZTHXQMGa2O6JZS20RkoWVtItLyAXMy2pnq7K2M5MFkcb6wlHu/yqc
  on:
    branch: main
