version: 5.5.0-{build}
branches:
  only:
  - main
  - dev
image: Visual Studio 2019
install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
#  - del /S /Q c:\tools\vcpkg\installed
  - .\vcpkg.exe install --recurse fontconfig:%PLATFORM%-windows
  - .\vcpkg.exe install --recurse pango:%PLATFORM%-windows
  - .\vcpkg.exe install --recurse libgd:%PLATFORM%-windows
#  - .\vcpkg.exe install --recurse wxwidgets:%PLATFORM%-windows
  - .\vcpkg.exe upgrade --no-dry-run
  - .\vcpkg.exe integrate install
cache:
  - c:\tools\vcpkg\installed\
  - C:\Users\appveyor\AppData\Local\vcpkg\archives\
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -mx
build:
  project: config\msvc\gnuplot\gnuplot.sln
  verbosity: normal
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
artifacts:
  - path: config\msvc\gnuplot\$(platform)\$(configuration)
    name: gnuplot_$(platform)_$(configuration)
    type: zip
deploy:
  provider: GitHub
  auth_token:
    secure: ZtmXQDde09xZodH/vnmq1egEAoBMWX8aSM0HP65R2nh3xVkaZi0CLNTV98LRh5TI
  on:
    branch: main
