version: 1.0.{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
install:
  - IF NOT EXIST vcpkg git clone https://github.com/Microsoft/vcpkg  
  - cd vcpkg
  - git pull
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install libgd:x86-windows-static libgd:x64-windows-static
  - vcpkg update
  - vcpkg integrate install
  - cd ..
cache:
  - vcpkg
build:
  project: config\msvc\gnuplot\gnuplot.sln
  verbosity: minimal
